# prometheus.yaml
global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: sglang
    static_configs:
      - targets:
          - "sglang-router:29000"
          - "sglang-chat:30000"
          - "sglang-embedding:30000"
